### ISSUE TITLE
Authenticate with Smartcard-HSM 4K (Nitrokey HSM v2) doesn't work

### ISSUE THREAD

**Issue by Pferdebockwurst** [OpenSC/pam_p11#15]
Hello, I have successfully installed pam_p11 on my Ubuntu 16.04 machine.

However, when I tried to use this pam module with my Nitrokey HSM v2, I was not able to successfully authenticate.

I've added the proper configuration in /etc/pam.d/sudo and ~/.ssh/authorized_keys. I can see that the HSM is being queried (red led on). Also the logs (opensc debug-Level set to 9) show, that the smartcard is recognized and also my SSH key on the HSM is found and identified as pin protected.

But after that, I'm not asked for the USER-PIN, but instead pam_p11 (pam_p11_openssh.so) quits and I'm asked for my superuser password.

Any ideas what could be wrong?

**Comment by frankmorgner** [comment]
Sounds like your authorized keys are not correctly set up. (see https://github.com/OpenSC/pam_p11#user-configuration-via-sshauthorized_keys). Check your syslog, where pam_p11 should output some error message.

**Comment by Pferdebockwurst** [comment]
Unfortunately there is no output in my syslog. And I have checked twice, that I have set up my authorized_keys correctly. I'm familiar with this kind of ssh authentication.

**Comment by frankmorgner** [comment]
Hmm, not sure where your system puts PAM's log messages...

You can test src/test-login, which should output some error on the commandline

**Comment by Pferdebockwurst** [comment]
Ok, i found out the log messages are in /var/log/auth.log.

The important part should be this one:

`Apr 16 20:51:54 XXX sudo: pam_p11_openssh(sudo:auth): no certificates found
Apr 16 20:51:55 XXX sudo: pam_unix(sudo:auth): auth could not identify password for [myusername]`

This is strange, as I am not trying to authenticate with a certificate but with an ssh key instead.

**Comment by frankmorgner** [comment]
You should use pam_p11 0.2.0, not 0.1.6!

prior to 0.2.0 pam_p11 had two modules; [one for pubkeys only and an other one for certificates](https://github.com/OpenSC/pam_p11/blob/d7899d47ee362ea8c47289729dbac69fb0ec07d1/README.md).

**Comment by Pferdebockwurst** [comment]
Indeed I did use 0.1.6, but where is the problem with that? Shouldn't that version also work?

**Comment by frankmorgner** [comment]
read the changelog and decide yourself https://github.com/OpenSC/pam_p11/releases/tag/pam_p11-0.2.0

Anyway, I've posted the link to the old documentation above.

**Comment by Pferdebockwurst** [comment]
I have just installed 0.2.0, but its still not working:

Apr 17 22:52:26 XXX sudo: pam_p11(sudo:auth): Searching UserPIN (XXX) for keys
Apr 17 22:52:26 XXX sudo: pam_p11(sudo:auth): Found SSH

After that, nothing happens, instead I am asked for my password to get superuser rights.

**Comment by frankmorgner** [comment]
It looks like sudo is performing a prelimenarity test whether the module has some credential (successful). I don't know why sudo doesn't continue authentication by asking for verification of said credential. Please try running `src/test-login` to exclude any possible errors in `/etc/pam.d/sudo`.
